#!/bin/bash

# Use osascript to show a dialog box for user input

INPUT=$(osascript <<EOF
tell application "System Events"
    activate
    set userInput to text returned of (display dialog "Please enter the Live version (e.g. 12.0.20) and your authorization token, and press [ENTER] on your keyboard" default answer "")
end tell
EOF
)

# Split the input into version and token

VERSION=$(echo "$INPUT" | awk '{print $1}')
TOKEN=$(echo "$INPUT" | awk '{print $2}')

# Validate input

if [[ -z "$VERSION" || -z "$TOKEN" ]]; then
osascript -e 'tell app "System Events" to display dialog "Error: Both version and token must be provided."'
  exit 1
fi

# Print the variables to validate the input

echo "VERSION: $VERSION"
echo "TOKEN: $TOKEN"

osascript -e 'tell app "System Events" to display dialog "Thanks. Live '$VERSION' will be authorized for all users on this machine. Your token '$TOKEN' will be used to authorize Live. Please click OK, then click in the Terminal window and enter your Administrator password."'

# Create shared Unlock folder with empty Unlock.json file

mkdir -p "/Library/Application Support/Ableton/Live ${VERSION}/Unlock/"
touch "/Library/Application Support/Ableton/Live ${VERSION}/Unlock/Unlock.json"
chmod a+rw  "/Library/Application Support/Ableton/Live ${VERSION}/Unlock/Unlock.json"
rm -f "/Library/Application Support/Ableton/Live ${VERSION}/Unlock/Unlock.cfg" 2>/dev/null

# Create shared preferences folder and add Options.txt entries

mkdir -p /Library/Preferences/Ableton/Live ${VERSION}/
chmod a+rw "/Library/Preferences/Ableton/Live ${VERSION}/"

# Add Options.txy entry
echo "-_DisableAutoUpdates" > "/Library/Preferences/Ableton/Live ${VERSION}/Options.txt"

# This bit will be for adding proxy awareness
# echo "-HttpsProxy=xxx.xxx.xx.x" | sudo tee -a "/Library/Preferences/Ableton/Live $VERSION/Options.txt"

# Add authorization token, launch Live
"/Applications/Ableton Live 12 ${EDITION}.app/Contents/MacOS/Live --authorization-token=${TOKEN}

# Capture the exit code
LIVE_EXIT_CODE=$?

 # Check the exit code
if [ ${LIVE_EXIT_CODE} -ne 0 ]; then
    echo "Ableton ${EDITION} authorization failed with exit code ${LIVE_EXIT_CODE}"
    exit ${LIVE_EXIT_CODE}
else
    echo "Ableton ${EDITION} was successfully authorized."
    exit 0
fi
